import { z } from "zod";

/**
 * Gallery — single source of truth for the /gallery page.
 *
 * Every item below is real photography/video from Navatara's Indian Food
 * Festival — 2024 and 2025, both supplied directly by the client and kept
 * distinguishable via `year` (the page's Year filter reads this).
 *
 * 2024: two clips from that upload batch (Parliament Hill "International
 * Day of Yoga" footage) were left out — that's a different Navatara-run
 * event, not the food festival, so including them would misrepresent what's
 * shown.
 *
 * 2025: one submitted photo turned out to be the SAME kind of yoga/wellness
 * session, but this time on the festival grounds itself (festival tents
 * visible behind the group) rather than at a separate Parliament Hill event
 * — that one genuinely is festival content, so it's included (`yoga-grounds`).
 *
 * `category` is inferred from what's actually in each shot — the uploads
 * don't come pre-tagged, so these are a best-effort read of the footage
 * itself, not invented themes with nothing behind them.
 *
 * `width`/`height` are the real encoded pixel dimensions of each asset in
 * /public/media/gallery/<year>/ — the masonry grid uses these to size each
 * tile's aspect ratio up front (via `aspect-ratio` in CSS), so nothing
 * shifts on load and nothing gets stretched or cropped.
 */

export const GALLERY_CATEGORIES = [
  "Crowd",
  "Performances",
  "Food",
  "Kids Zone",
  "Volunteers",
  "Cultural Shows",
] as const;

const CategorySchema = z.enum(GALLERY_CATEGORIES);

export const GALLERY_YEARS = ["2024", "2025"] as const;

const GalleryItemSchema = z.object({
  id: z.string(),
  type: z.enum(["photo", "video"]),
  title: z.string(),
  year: z.enum(GALLERY_YEARS),
  category: CategorySchema,
  alt: z.string(),
  width: z.number(),
  height: z.number(),
  /** Photos only — the full-resolution image. */
  image: z.string().optional(),
  /** Videos only — the playable source. */
  video: z.string().optional(),
  /** Videos only — the paused-frame poster shown in the grid. */
  thumbnail: z.string().optional(),
  /** Videos only — display duration, e.g. "0:15". */
  duration: z.string().optional(),
});

const BASE = "/media/gallery/2024";
const BASE_2025 = "/media/gallery/2025";

export const galleryItems = z.array(GalleryItemSchema).parse([
  // ---------- Photos ----------
  {
    id: "friends-group",
    type: "photo",
    title: "Friends at the Festival",
    year: "2024",
    category: "Crowd",
    alt: "Six friends sitting together on the grass at the festival",
    image: `${BASE}/friends-group.jpg`,
    width: 1024,
    height: 603,
  },
  {
    id: "family-portrait",
    type: "photo",
    title: "A Family Outing",
    year: "2024",
    category: "Crowd",
    alt: "Three generations of a family posing together at the festival",
    image: `${BASE}/family-portrait.jpg`,
    width: 1024,
    height: 775,
  },
  {
    id: "crowd-candid",
    type: "photo",
    title: "Wandering the Grounds",
    year: "2024",
    category: "Crowd",
    alt: "Festival-goers walking across the grounds past the vendor tents",
    image: `${BASE}/crowd-candid.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "crowd-field",
    type: "photo",
    title: "The Festival Grounds",
    year: "2024",
    category: "Crowd",
    alt: "A large crowd gathered across the open festival field",
    image: `${BASE}/crowd-field.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "crowd-sunset",
    type: "photo",
    title: "Golden Hour Crowd",
    year: "2024",
    category: "Crowd",
    alt: "Visitors seated on the grass watching the stage at sunset",
    image: `${BASE}/crowd-sunset.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "stage-dancers",
    type: "photo",
    title: "On Stage",
    year: "2024",
    category: "Performances",
    alt: "Two dancers mid-performance in traditional dress on the festival stage",
    image: `${BASE}/stage-dancers.jpg`,
    width: 1200,
    height: 1600,
  },

  // ---------- Videos ----------
  {
    id: "dance-performance-1",
    type: "video",
    title: "Live Dance Performance",
    year: "2024",
    category: "Performances",
    alt: "Dancers performing on the main stage as the crowd watches",
    video: `${BASE}/dance-performance-1.mp4`,
    thumbnail: `${BASE}/dance-performance-1-poster.jpg`,
    duration: "0:15",
    width: 1280,
    height: 720,
  },
  {
    id: "bhangra-performance",
    type: "video",
    title: "Bhangra on the Main Stage",
    year: "2024",
    category: "Performances",
    alt: "Bhangra dancers in white and orange performing on stage",
    video: `${BASE}/bhangra-performance.mp4`,
    thumbnail: `${BASE}/bhangra-performance-poster.jpg`,
    duration: "0:12",
    width: 1280,
    height: 720,
  },
  {
    id: "dhol-procession",
    type: "video",
    title: "Dhol Procession",
    year: "2024",
    category: "Performances",
    alt: "A dhol drum procession with flags moving through the crowd",
    video: `${BASE}/dhol-procession.mp4`,
    thumbnail: `${BASE}/dhol-procession-poster.jpg`,
    duration: "0:13",
    width: 1280,
    height: 720,
  },
  {
    id: "festival-grounds-video",
    type: "video",
    title: "Festival Atmosphere",
    year: "2024",
    category: "Crowd",
    alt: "Wide view of the festival grounds with vendor tents and seated visitors",
    video: `${BASE}/festival-grounds.mp4`,
    thumbnail: `${BASE}/festival-grounds-poster.jpg`,
    duration: "0:05",
    width: 1280,
    height: 720,
  },
  {
    id: "food-vendor-serving",
    type: "video",
    title: "Fresh From the Stall",
    year: "2024",
    category: "Food",
    alt: "A vendor serving a freshly prepared drink to a festival visitor",
    video: `${BASE}/food-vendor-serving.mp4`,
    thumbnail: `${BASE}/food-vendor-serving-poster.jpg`,
    duration: "0:16",
    width: 1280,
    height: 720,
  },
  {
    id: "roti-griddle",
    type: "video",
    title: "Made Fresh on the Griddle",
    year: "2024",
    category: "Food",
    alt: "Roti being cooked fresh on a large griddle at a food stall",
    video: `${BASE}/roti-griddle.mp4`,
    thumbnail: `${BASE}/roti-griddle-poster.jpg`,
    duration: "0:39",
    width: 720,
    height: 1280,
  },

  // ---------- 2025 Photos ----------
  {
    id: "dancer-portrait",
    type: "photo",
    title: "Mid-Performance",
    year: "2025",
    category: "Performances",
    alt: "A performer in embroidered white, mid-move, on the festival grounds",
    image: `${BASE_2025}/dancer-portrait.jpg`,
    width: 1220,
    height: 1600,
  },
  {
    id: "kids-high-five",
    type: "photo",
    title: "High Fives All Around",
    year: "2025",
    category: "Kids Zone",
    alt: "A performer high-fiving young dancers in red and white tracksuits",
    image: `${BASE_2025}/kids-high-five.jpg`,
    width: 1220,
    height: 1600,
  },
  {
    id: "team-group-photo",
    type: "photo",
    title: "The Team Behind It All",
    year: "2025",
    category: "Volunteers",
    alt: "The organising team posing together under the festival's main tent",
    image: `${BASE_2025}/team-group-photo.jpg`,
    width: 1920,
    height: 1080,
  },
  {
    id: "yoga-session",
    type: "photo",
    title: "Morning Wellness Session",
    year: "2025",
    category: "Crowd",
    alt: "A large group taking part in a guided wellness session on the festival grounds",
    image: `${BASE_2025}/yoga-session.jpg`,
    width: 1920,
    height: 1080,
  },
  {
    id: "yoga-grounds",
    type: "photo",
    title: "Stretching It Out",
    year: "2025",
    category: "Crowd",
    alt: "Festival-goers stretching on mats on the festival grounds, tents visible behind them",
    image: `${BASE_2025}/yoga-grounds.jpg`,
    width: 1920,
    height: 1440,
  },
  {
    id: "green-sari-dancer",
    type: "photo",
    title: "Classical Solo",
    year: "2025",
    category: "Performances",
    alt: "A classical dancer in a green and gold sari performing under the stage tent at dusk",
    image: `${BASE_2025}/green-sari-dancer.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "volunteers-group-1",
    type: "photo",
    title: "On-Site Team",
    year: "2025",
    category: "Volunteers",
    alt: "Four volunteers posing together under the festival's main tent banner",
    image: `${BASE_2025}/volunteers-group-1.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "flag-procession",
    type: "photo",
    title: "Flags Held High",
    year: "2025",
    category: "Performances",
    alt: "A performer in white and orange raising a drumstick and flag during a procession",
    image: `${BASE_2025}/flag-procession.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "chatting-with-visitors",
    type: "photo",
    title: "Meeting the Community",
    year: "2025",
    category: "Volunteers",
    alt: "Organisers speaking with visitors near a food vendor's tent",
    image: `${BASE_2025}/chatting-with-visitors.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "fried-snacks-platter",
    type: "photo",
    title: "Fresh Off the Pan",
    year: "2025",
    category: "Food",
    alt: "A platter of fried snacks arranged around a bowl of spiced filling",
    image: `${BASE_2025}/fried-snacks-platter.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "folk-costume-couple",
    type: "photo",
    title: "In Full Regalia",
    year: "2025",
    category: "Cultural Shows",
    alt: "A couple in bright pink and white traditional folk costume holding ceremonial canes",
    image: `${BASE_2025}/folk-costume-couple.jpg`,
    width: 988,
    height: 1600,
  },
  {
    id: "kids-team-food-signs",
    type: "photo",
    title: "Name That Dish",
    year: "2025",
    category: "Kids Zone",
    alt: "A large group of children and adults celebrating, holding up dish name signs",
    image: `${BASE_2025}/kids-team-food-signs.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "volunteers-group-2",
    type: "photo",
    title: "Festival Crew",
    year: "2025",
    category: "Volunteers",
    alt: "Three volunteers in festival t-shirts standing together on the grounds",
    image: `${BASE_2025}/volunteers-group-2.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "henna-art",
    type: "photo",
    title: "Henna on the Spot",
    year: "2025",
    category: "Crowd",
    alt: "A visitor having intricate henna applied to their hand at a festival stall",
    image: `${BASE_2025}/henna-art.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "tents-and-crowd",
    type: "photo",
    title: "Under the Tents",
    year: "2025",
    category: "Crowd",
    alt: "Rows of white tents with visitors seated and eating beneath them",
    image: `${BASE_2025}/tents-and-crowd.jpg`,
    width: 1920,
    height: 1280,
  },
  {
    id: "sponsor-rewards-booth",
    type: "photo",
    title: "Win Big While You Feast",
    year: "2025",
    category: "Crowd",
    alt: "A sponsor booth volunteer holding up a rewards programme poster",
    image: `${BASE_2025}/sponsor-rewards-booth.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "zaika-stall",
    type: "photo",
    title: "Zaika's Counter",
    year: "2025",
    category: "Food",
    alt: "A vendor smiling behind the counter at the Zaika food stall, drink dispensers in front",
    image: `${BASE_2025}/zaika-stall.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "spiderman-face-paint",
    type: "photo",
    title: "Kids Zone Face Painting",
    year: "2025",
    category: "Kids Zone",
    alt: "A child having a Spider-Man design face-painted at the Kids Zone",
    image: `${BASE_2025}/spiderman-face-paint.jpg`,
    width: 1066,
    height: 1599,
  },
  {
    id: "food-sampling-prep",
    type: "photo",
    title: "Plating the Samples",
    year: "2025",
    category: "Food",
    alt: "A volunteer plating small food samples into bowls at a tasting table",
    image: `${BASE_2025}/food-sampling-prep.jpg`,
    width: 1066,
    height: 1599,
  },

  // ---------- 2025 Videos ----------
  {
    id: "highlights-reel-2025",
    type: "video",
    title: "2025 Highlights Reel",
    year: "2025",
    category: "Performances",
    alt: "A highlight reel of dance performances from the 2025 festival",
    video: `${BASE_2025}/2025-highlights-reel.mp4`,
    thumbnail: `${BASE_2025}/2025-highlights-reel-poster.jpg`,
    duration: "0:27",
    width: 720,
    height: 1280,
  },
  {
    id: "dance-performance-2025",
    type: "video",
    title: "Dance Crew on the Grounds",
    year: "2025",
    category: "Performances",
    alt: "Three dancers in red and black performing a choreographed routine on the festival grounds",
    video: `${BASE_2025}/dance-performance-2025.mp4`,
    thumbnail: `${BASE_2025}/dance-performance-2025-poster.jpg`,
    duration: "0:11",
    width: 1280,
    height: 720,
  },
  {
    id: "dhol-stage-2025",
    type: "video",
    title: "Dhol on the Main Stage",
    year: "2025",
    category: "Performances",
    alt: "A drummer playing the dhol on the main stage under the Navatara festival banner at dusk",
    video: `${BASE_2025}/dhol-stage-2025.mp4`,
    thumbnail: `${BASE_2025}/dhol-stage-2025-poster.jpg`,
    duration: "0:19",
    width: 720,
    height: 1280,
  },
  {
    id: "drone-aerial-2025",
    type: "video",
    title: "The Festival From Above",
    year: "2025",
    category: "Crowd",
    alt: "Aerial drone footage of the festival grounds, showing rows of vendor tents and crowds of visitors",
    video: `${BASE_2025}/drone-aerial-2025.mp4`,
    thumbnail: `${BASE_2025}/drone-aerial-2025-poster.jpg`,
    duration: "0:11",
    width: 1280,
    height: 720,
  },
  {
    id: "kids-dance-crew-2025",
    type: "video",
    title: "Kids Dance Crew",
    year: "2025",
    category: "Performances",
    alt: "A youth dance group in red and white performing a choreographed routine as a crowd watches",
    video: `${BASE_2025}/kids-dance-crew-2025.mp4`,
    thumbnail: `${BASE_2025}/kids-dance-crew-2025-poster.jpg`,
    duration: "0:06",
    width: 1280,
    height: 720,
  },
  {
    id: "food-sauce-drizzle-2025",
    type: "video",
    title: "Finishing Touches",
    year: "2025",
    category: "Food",
    alt: "A vendor drizzling sauce over a freshly prepared food item at a festival stall",
    video: `${BASE_2025}/food-sauce-drizzle-2025.mp4`,
    thumbnail: `${BASE_2025}/food-sauce-drizzle-2025-poster.jpg`,
    duration: "0:03",
    width: 1280,
    height: 720,
  },
  {
    id: "crochet-craft-stall-2025",
    type: "video",
    title: "Handmade at the Craft Stall",
    year: "2025",
    category: "Crowd",
    alt: "A close-up of handmade crochet flowers and keychains displayed at a craft vendor's stall",
    video: `${BASE_2025}/crochet-craft-stall-2025.mp4`,
    thumbnail: `${BASE_2025}/crochet-craft-stall-2025-poster.jpg`,
    duration: "0:12",
    width: 720,
    height: 1280,
  },
  {
    id: "henna-art-2025",
    type: "video",
    title: "Henna, One Stroke at a Time",
    year: "2025",
    category: "Crowd",
    alt: "A henna artist applying an intricate design to a visitor's hand at a festival stall",
    video: `${BASE_2025}/henna-art-2025.mp4`,
    thumbnail: `${BASE_2025}/henna-art-2025-poster.jpg`,
    duration: "0:07",
    width: 720,
    height: 1280,
  },
  {
    id: "folk-dance-solo-2025",
    type: "video",
    title: "A Solo in Pink and Gold",
    year: "2025",
    category: "Cultural Shows",
    alt: "A dancer in vibrant pink traditional attire performing a solo folk dance with a decorated staff",
    video: `${BASE_2025}/folk-dance-solo-2025.mp4`,
    thumbnail: `${BASE_2025}/folk-dance-solo-2025-poster.jpg`,
    duration: "0:14",
    width: 720,
    height: 1280,
  },
  {
    id: "acoustic-performer-2025",
    type: "video",
    title: "Live Acoustic Set",
    year: "2025",
    category: "Performances",
    alt: "A musician singing and playing acoustic guitar near the festival's main entrance tent",
    video: `${BASE_2025}/acoustic-performer-2025.mp4`,
    thumbnail: `${BASE_2025}/acoustic-performer-2025-poster.jpg`,
    duration: "0:18",
    width: 720,
    height: 1280,
  },
  {
    id: "jewelry-stall-2025",
    type: "video",
    title: "Bangles on Display",
    year: "2025",
    category: "Crowd",
    alt: "A close-up of gold bangles and bracelets on display at a jewelry vendor's stall",
    video: `${BASE_2025}/jewelry-stall-2025.mp4`,
    thumbnail: `${BASE_2025}/jewelry-stall-2025-poster.jpg`,
    duration: "0:09",
    width: 720,
    height: 1280,
  },
  {
    id: "craft-stall-shoppers-2025",
    type: "video",
    title: "Browsing the Craft Stall",
    year: "2025",
    category: "Crowd",
    alt: "Visitors browsing handmade crochet items and accessories at a vendor tent",
    video: `${BASE_2025}/craft-stall-shoppers-2025.mp4`,
    thumbnail: `${BASE_2025}/craft-stall-shoppers-2025-poster.jpg`,
    duration: "0:12",
    width: 720,
    height: 1280,
  },
  {
    id: "edition-2025-recap",
    type: "video",
    title: "Highlights From the 2025 Edition",
    year: "2025",
    category: "Crowd",
    alt: "A recap video of the 2025 festival featuring food, kids' face painting, and visitors dancing on the grounds",
    video: `${BASE_2025}/edition-2025-recap.mp4`,
    thumbnail: `${BASE_2025}/edition-2025-recap-poster.jpg`,
    duration: "0:54",
    width: 720,
    height: 1280,
  },
  {
    id: "shaaz-menu-board-2025",
    type: "video",
    title: "Shaaz The Indian Cuisine",
    year: "2025",
    category: "Food",
    alt: "A chalkboard menu for Shaaz The Indian Cuisine listing dosas, mains, and desserts, with a plate of food in the foreground",
    video: `${BASE_2025}/shaaz-menu-board-2025.mp4`,
    thumbnail: `${BASE_2025}/shaaz-menu-board-2025-poster.jpg`,
    duration: "0:10",
    width: 720,
    height: 1280,
  },
  {
    id: "food-tray-chaat-2025",
    type: "video",
    title: "A Tray Full of Chaat",
    year: "2025",
    category: "Food",
    alt: "A festival visitor holding a tray of chaat and sauces on the festival grounds",
    video: `${BASE_2025}/food-tray-chaat-2025.mp4`,
    thumbnail: `${BASE_2025}/food-tray-chaat-2025-poster.jpg`,
    duration: "0:15",
    width: 720,
    height: 1280,
  },
  {
    id: "evening-dance-2025",
    type: "video",
    title: "Dance Under the Evening Lights",
    year: "2025",
    category: "Cultural Shows",
    alt: "Dancers in white performing on stage at dusk under the Navatara festival banner, crowd watching",
    video: `${BASE_2025}/evening-dance-2025.mp4`,
    thumbnail: `${BASE_2025}/evening-dance-2025-poster.jpg`,
    duration: "0:11",
    width: 720,
    height: 1280,
  },
]);

export type GalleryItem = (typeof galleryItems)[number];
